name: "Tag and release"
description: "Create a GitHub release with optional assets"
author: Jakob Lilliemarck
inputs:
  tag_name:
    description: "The name of the git tag."
    required: true

  release_name:
    description: "Name of the release."
    required: false

  release_body:
    description: "Description of contents."
    required: false

  release_artifacts:
    description: "Comma separated list of files include as release assets"
    required: false

  generate_release_notes:
    description: "Automatically generate release names and notes using"
    required: false

outputs:
  release_id:
    description: "The release id of the newly created GitHub release"

runs:
  using: "node20"
  main: "dist/index.js"
