name: "Release"
description: "Create a GitHub release with optional assets"
inputs:
  artifacts:
    description: "Comma separated list of files include as release assets"
outputs:
  location:
    description: "The URI of the GitHub release"
runs:
  using: "node20"
  main: "dist/index.js"
