name: Create a release

on: [push]

jobs:
 main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          echo "foo" > ./foo.txt
          echo "bar" > ./bar.txt
          echo "bax" > ./baz.txt
          ls -R

      - uses: jakob-lilliemarck/action-ez-release@v1
        with:
          tag_name: _test
          release_artifacts: |
            foo.txt
            bar.txt
            baz.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}